name: baba
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.3.0

  get: ^4.5.1
  flutter_screenutil: ^5.0.1
  cached_network_image: ^3.2.0

  sync_scroll: ^2.0.0+2
  google_fonts: ^2.1.0
  flutter_rating_bar: ^4.0.0

  bottom_nav: ^1.0.1
  curved_navigation_bar: ^1.0.1
  carousel_slider: ^4.0.0

  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  introduction_screen: ^2.1.0
  getwidget: ^2.0.4


  google_sign_in: ^5.0.4
  flutter_facebook_auth: ^3.5.7
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5
  shared_preferences: ^2.0.11
  geolocator: ^8.0.1
  url_launcher: ^6.0.18
  flutter_html: ^3.0.0-alpha.2
#  flutter_stripe: ^2.1.1
  firebase_messaging: ^11.2.6
  stripe_payment: ^1.1.4
  flutter_credit_card: ^3.0.1
  platform: ^3.1.0
  device_info_plus: ^3.2.2
  dotted_border: ^2.0.0+2
  font_awesome_flutter: ^9.2.0
  ionicons: ^0.1.2
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  
  uses-material-design: true

  assets:
    - assets/font/
    - assets/images/
    - assets/svgs/

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
  